apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: greetingwebui-config-claim0
    name: greetingwebui-config-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: greetingwebui
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: iaghcp-docker-glp.jfrog.io/greetingwebui/greetingwebui:{{TAG_SERVICE}}
      from:
        kind: DockerImage
        name: iaghcp-docker-glp.jfrog.io/greetingwebui/greetingwebui:{{TAG_SERVICE}}
      generation: null
      importPolicy: {}
      name: "{{TAG_SERVICE}}"
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: static-config
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: iaghcp-docker-technical-architecture.jfrog.io/static-config:1.0.0
      from:
        kind: DockerImage
        name: iaghcp-docker-technical-architecture.jfrog.io/static-config:1.0.0
      generation: null
      importPolicy: {}
      name: "1.0.0"
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: greetingwebui
  spec:
    replicas: 1
    selector:
      deploymentconfig: greetingwebui
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: greetingwebui
      spec:
        containers:
        - image: iaghcp-docker-technical-architecture.jfrog.io/static-config:1.0.0
          name: static-config
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: "2"
              memory: "2Gi"
          env:
          - name: GLOBALCONF
            value: {{TAG_GLOBALCONF}}
          - name: SYSTEMCONF
            value: {{TAG_SYSTEMCONF}}
          volumeMounts:
          - mountPath: /usr/src/app/conf
            name: greetingwebui-config-claim0
        - image: iaghcp-docker-glp.jfrog.io/greetingwebui/greetingwebui:{{TAG_SERVICE}}
          command: [ "/bin/bash"]
          args: ["-c", "sudo service supervisor start && sudo service nginx start && bash"]
          name: greetingwebui
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: "2"
              memory: "2Gi"
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /usr/src/conf
            name: greetingwebui-config-claim0
        volumes:
        - name: greetingwebui-config-claim0
          persistentVolumeClaim:
            claimName: greetingwebui-config-claim0
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - greetingwebui
        from:
          kind: ImageStreamTag
          name: greetingwebui:{{TAG_SERVICE}}
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: greetingwebui
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: greetingwebui
  status:
    loadBalancer: {}
kind: List
metadata: {}
