apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: greetingwebui
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: iaghcp-docker-glp.jfrog.io/greetingwebui/greetingwebui:{{TAG_SERVICE}}
      from:
        kind: DockerImage
        name: iaghcp-docker-glp.jfrog.io/greetingwebui/greetingwebui:{{TAG_SERVICE}}
      generation: null
      importPolicy: {}
      name: "{{TAG_SERVICE}}"
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: greetingwebui
  spec:
    replicas: 1
    selector:
      deploymentconfig: greetingwebui
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: greetingwebui
      spec:
        containers:
        - image: iaghcp-docker-glp.jfrog.io/greetingwebui/greetingwebui:{{TAG_SERVICE}}
          command: [ "/bin/bash"]
          args: ["-c", "service supervisor start && service nginx start && bash"]
          name: greetingwebui
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: "2"
              memory: "2Gi"
          ports:
          - containerPort: 8080
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - greetingwebui
        from:
          kind: ImageStreamTag
          name: greetingwebui:{{TAG_SERVICE}}
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: greetingwebui
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: greetingwebui
  status:
    loadBalancer: {}
kind: List
metadata: {}
